coverage:
   precision: 2
   round: down
   range: "80...100"
   ignore:
     - "Helpers/.*"
     - "Sources/LoadableImage/Components/.*"
     - "Sources/LoadableImage/Loadable/Providers/.*"
     - "Tests"
