language:  swift
os: osx
osx_image: xcode12
xcode_sdk: iphonesimulator14.0
cache:
directories:
# General SwiftPM
# Danger Swift plugins, like Yams
- .build
- ~/.danger-swift

before_script:
  - set -o pipefail

jobs:
  include:
# ==============================================================================
    - stage: danger
      install:
        - npm install -g danger
        - swift build
      script:
        - swift run danger-swift ci
# ==============================================================================
    - stage: test
      if: NOT (tag IS present)
      env: JOB=iOS Tests
      script:
        - travis_retry xcodebuild -scheme LoadableImage -destination "platform=iOS Simulator,name=iPhone 11 Pro" -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" test | xcpretty -f `xcpretty-travis-formatter`
      after_success:
        - bash <(curl -s https://codecov.io/bash)
# ==============================================================================
    - stage: test
      if: NOT (tag IS present)
      env: JOB=macOS Tests
      script:
        - travis_retry xcodebuild -scheme LoadableImage -enableCodeCoverage YES CODE_SIGNING_REQUIRED=NO CODE_SIGN_IDENTITY="" ENABLE_TESTABILITY=YES test | xcpretty -f `xcpretty-travis-formatter`
      after_success:
        - bash <(curl -s https://codecov.io/bash)
# ==============================================================================
