language:
  - swift
osx_image: xcode11.1
script:
  - xcodebuild -scheme LoadableImage -sdk iphonesimulator -destination 'platform=iOS Simulator,name=iPhone X,OS=13.1' build test
after_success:
  - bash <(curl -s https://codecov.io/bash)
