language: swift
xcode_project: LoadableImage.xcodeproj
xcode_scheme: LoadableImageTests
xcode_destination: platform=iOS Simulator,OS=11.3,name=iPhone X

sudo: false # faster builds

script: "mvn cobertura:cobertura"

after_success:
  - bash <(curl -s https://codecov.io/bash)
