# For a detailed guide to building and testing on iOS, read the docs:
# https://circleci.com/docs/2.0/testing-ios/

version: 2.1

orbs:
  codecov: codecov/codecov@1.0.2

jobs:
  build-and-test:
    macos:
      xcode: 12.0.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: test
    steps:
      - checkout
      - run: bundle install
      - run:
          name: pre-start simulator
          command: xcrun instruments -w "iPhone 11 Pro (13.3) [" || true
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_test_results:
          path: output/scan
      - store_artifacts:
          path: output
      - codecov/upload:
          file: coverage.xml

  adhoc:
    macos:
      xcode: 11.3.0
    environment:
      FL_OUTPUT_DIR: output
      FASTLANE_LANE: adhoc
    steps:
      - checkout
      - run: bundle install
      - run:
          name: Fastlane
          command: bundle exec fastlane $FASTLANE_LANE
      - store_artifacts:
          path: output

  swiftlint:
    docker:
      - image: bytesguy/swiftlint:latest
    steps:
      - checkout
      - run: swiftlint lint --reporter junit | tee result.xml
      - store_artifacts:
          path: result.xml
      - store_test_results:
          path: result.xml

  danger:
    docker:
      - image: bytesguy/danger:latest
    steps:
      - checkout
      - run: danger

workflows:
  build-test-adhoc:
    jobs:
      - swiftlint
      - danger
      - build-and-test
      - adhoc:
          filters:
            branches:
              only: development
          requires:
            - build-and-test
