name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Linting
        uses: norio-nomura/action-swiftlint@3.1.0

  Test:
    name: Tests
    runs-on: xcode-latest
    steps:
      - name: Run tests
        run: swift test --enable-code-coverage
      - name: Collect coverage
        uses: maxep/spm-lcov-action@0.3.0
        with:
          output-file: ./coverage/lcov.info
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage/lcov.info
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
