name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    name: SwiftLint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Linting
        uses: norio-nomura/action-swiftlint@3.1.0

  Test:
    name: Tests
    runs-on: macOS-latest
    steps:
      - name: Select Xcode 12
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Checkout action
        uses: actions/checkout@v2
      - name: Run tests
        run: swift test --enable-test-discovery --enable-code-coverage
      - name: Upload test coverage
        uses: mattpolzin/swift-codecov-action@0.4.0
