name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    name: Swiftlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
        
  Danger:
    name: Danger
    runs-on: ubuntu-latest
    steps:
      - name: Danger action
        uses: MeilCli/danger-action@v4
        
  Test:
    name: Test action
    runs-on: macos-latest
    strategy: 
      matrix:
        destination: ['platform=iOS Simulator,OS=13.6,name=iPhone 11']

    steps:
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Run tests
        run: |
          xcodebuild clean test -scheme LoadableImage -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
          destination: ${{ matrix.destination }}
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
