name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
    paths:
      - '.github/workflows/swiftlint.yml'
      - '.swiftlint.yml'
      - '**/*.swift'

jobs:
  SwiftLint:
    name: Swiftlint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout action
        uses: actions/checkout@v2
      - name: SwiftLint
        uses: norio-nomura/action-swiftlint@3.1.0
          
  Build:
    name: Build
    env:
      SCHEME: "LoadableImage"
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
    runs-on: macOS-latest
    steps:
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Build application
        run: |
          set -o pipefail && xcodebuild clean -scheme $SCHEME -destination "platform=iOS Simulator,name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH build-for-testing | xcpretty --color --simple
      - name: Upload products
        uses: actions/upload-artifact@v1
        with:
          name: Products
          path: DerivedData/Build/Products

  Test:
    name: Test
    env:
      DEVICE: "iPhone 11"
      DERIVED_DATA_PATH: "DerivedData"
      UNIT_TEST_TARGET: "LoadableImageTests"
    runs-on: macos-latest
    needs: Build
    steps:
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode_12.app
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Download products
        uses: actions/download-artifact@v1
        with:
          name: Products
      - name: Run tests
        run: |
          set -o pipefail && xcodebuild test-without-building -xctestrun $(find . -type f -name "*.xctestrun") -destination "platform=iOS Simulator,name=$DEVICE" -derivedDataPath $DERIVED_DATA_PATH -enableCodeCoverage YES -only-testing:$UNIT_TEST_TARGET | xcpretty --color --simple
          
  Codecov:
    name: Codecov
    runs-on: macos-latest
    needs: Test
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
      - name: Download products
        uses: actions/download-artifact@v1
        with:
          name: Products
      - name: Setup Python
        uses: actions/setup-python@master
        with:
          python-version: 3.7
      - name: Generate coverage report
        run: |
          pip install pytest
          pip install pytest-cov
          pytest --cov=./ --cov-report=xml
      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
