name: Swift

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    name: Test
    runs-on: macos-latest
    strategy: 
      matrix:
        destination: ['platform=iOS Simulator,OS=13.6,name=iPhone 11']

    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Select Xcode
        run: sudo xcode-select -s /Applications/Xcode.app
      - name: Run tests
        run: |
          xcodebuild clean test -project LoadableImage.xcodeproj -scheme LoadableImage -destination "${destination}" CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
        env: 
          destination: ${{ matrix.destination }}
      - uses: codecov/codecov-action@v1
        with:
          file: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
